version: "3.8"

services:
  postgres-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  api:
    image: ${DOCKER_HUB_USERNAME}/hr-system-api:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
    env_file:
      - ./.env

  nginx:
    image: ${DOCKER_HUB_USERNAME}/hr-system-nginx-frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - api

volumes:
  postgres-db:
  static_value:
  media_value: