name: hr-system workflow

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

jobs:
  deploy-to-remote-server:
    name: Deploy project to remote server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker compose stop
            touch .env
            echo "${{ secrets.ENV_FILE }}" > .env
            sudo docker-compose up -d --build
